// Sample data - In real app, this would come from a database
export const sampleFeedback = [
  {
    id: '1',
    title: 'Add Dark Mode Support',
    description: 'It would be great to have a dark mode option for better viewing in low-light conditions.',
    category: 'Feature',
    status: 'in-progress' as const,
    upvotes: 42,
    author: 'John Doe',
    date: '2 days ago',
  },
  {
    id: '2',
    title: 'Improve Search Functionality',
    description: 'The current search is a bit slow. Consider adding filters and better indexing.',
    category: 'Enhancement',
    status: 'pending' as const,
    upvotes: 28,
    author: 'Jane Smith',
    date: '5 days ago',
  },
  {
    id: '3',
    title: 'Mobile App Version',
    description: 'A native mobile app would make it easier to submit feedback on the go.',
    category: 'Feature',
    status: 'pending' as const,
    upvotes: 67,
    author: 'Mike Johnson',
    date: '1 week ago',
  },
  {
    id: '4',
    title: 'Email Notifications',
    description: 'Get notified when someone comments on your feedback or when status changes.',
    category: 'Feature',
    status: 'completed' as const,
    upvotes: 93,
    author: 'Sarah Williams',
    date: '2 weeks ago',
  },
  {
    id: '5',
    title: 'Export Feedback to CSV',
    description: 'Allow admins to export all feedback data to CSV format for analysis.',
    category: 'Feature',
    status: 'completed' as const,
    upvotes: 15,
    author: 'David Brown',
    date: '3 weeks ago',
  },
  {
    id: '6',
    title: 'Better Loading Performance',
    description: 'The page takes too long to load with many feedback items. Need optimization.',
    category: 'Bug',
    status: 'in-progress' as const,
    upvotes: 34,
    author: 'Emily Davis',
    date: '4 days ago',
  },
];
